"""coach reports

Revision ID: 851b404636bf
Revises: efa916c8d9b5
Create Date: 2026-06-16 22:36:49.299584

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.base

# revision identifiers, used by Alembic.
revision: str = '851b404636bf'
down_revision: Union[str, None] = 'efa916c8d9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_reports',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('lap_id', app.models.base.GUID(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_reports_lap_id'), 'coach_reports', ['lap_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_reports_lap_id'), table_name='coach_reports')
    op.drop_table('coach_reports')
    # ### end Alembic commands ###
