"""initial schema

Revision ID: efa916c8d9b5
Revises: 
Create Date: 2026-06-16 22:20:19.356040

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.base

# revision identifiers, used by Alembic.
revision: str = 'efa916c8d9b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=8), server_default='ru', nullable=False),
    sa.Column('plan', sa.String(length=16), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sessions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('game', sa.String(length=16), nullable=False),
    sa.Column('track', sa.String(length=120), nullable=True),
    sa.Column('car_or_team', sa.String(length=120), nullable=True),
    sa.Column('session_type', sa.String(length=40), nullable=True),
    sa.Column('weather', sa.String(length=40), nullable=True),
    sa.Column('client_session_uuid', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_client_session_uuid'), 'sessions', ['client_session_uuid'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('laps',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('client_lap_uuid', sa.String(length=64), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laps_client_lap_uuid'), 'laps', ['client_lap_uuid'], unique=True)
    op.create_index(op.f('ix_laps_session_id'), 'laps', ['session_id'], unique=False)
    op.create_table('telemetry_traces',
    sa.Column('lap_id', app.models.base.GUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('hz', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_encoding', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lap_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_traces')
    op.drop_index(op.f('ix_laps_session_id'), table_name='laps')
    op.drop_index(op.f('ix_laps_client_lap_uuid'), table_name='laps')
    op.drop_table('laps')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_client_session_uuid'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
